export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_CART: "REMOVE_CART",
  FILTER_PRODUCT: "FILTER_PRODUCT",
  ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
  REMOVE_WISHLIST: "REMOVE_WISHLIST",
  USER_SIGNIN: "USER_SIGNIN",
  USER_SIGNOUT: "USER_SIGNOUT",
  EMPTY_CART: "EMPTY_CART",
};
